export const LOADMORE_PASSPORTS = 'LOADMORE_PASSPORTS';
export const REFRESH_PASSPORTS = 'REFRESH_PASSPORTS';
export const LOAD_PASSPORTS_SUCCESS = 'LOAD_PASSPORTS_SUCCESS';
export const LOAD_PASSPORTS_FAIL = 'LOAD_PASSPORTS_FAIL';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';